packages:
  - .
onlyBuiltDependencies:
  - vue-demi
overrides:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
allowBuilds:
  vue-demi: true
minimumReleaseAgeExclude:
  - concurrently@10.0.4
  - playwright-core@1.62.0
  - playwright@1.62.0
